### ISSUE TITLE
Could you create a c8yLWM2M Version for the Raspberry Pi ?

### ISSUE THREAD

**Issue by edbal002** [mstoffel-sag/c8yMQTT#5]
Hello Dev-Team,

this Python Agent is pretty good and can be used for good looking and easy to understand Tech-demos.

Would it be possible to make a LWM2M version with exactly this functionality?

Kind regards!

**Comment by mstoffel-sag** [comment]
Hi,

since LWM2M is available as a dedicated protocol integration. You should be able to use just that:

https://cumulocity.com/guides/10.7.0-beta/protocol-integration/lwm2m/

Kind Regards,

Marco
